version: '3.5'
services:
  database:
    image: 'postgres:15'
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - $HOME/docker/volumes/postgres15:/var/lib/postgresql/data
    ports:
      - "5432:5432"
