"""Create a baseline migrations

Revision ID: 0fc9421fd426
Revises: 
Create Date: 2023-08-24 11:18:30.032406

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fc9421fd426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diners_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diner_id', sa.Integer(), nullable=True),
    sa.Column('restriction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diner_id'], ['diners.id'], name='fk_diners_restrictions_diner_id'),
    sa.ForeignKeyConstraint(['restriction_id'], ['restrictions.id'], name='fk_diners_restrictions_restriction_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('diner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diner_id'], ['diners.id'], name='fk_reservations_diner_id'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_reservations_table_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurants_endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('endorsement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endorsement_id'], ['restrictions.id'], name='fk_restaurants_endorsements_endorsement_id'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['diners.id'], name='fk_restaurants_endorsements_restaurant_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants_endorsements')
    op.drop_table('reservations')
    op.drop_table('diners_restrictions')
    op.drop_table('tables')
    op.drop_table('restrictions')
    op.drop_table('restaurants')
    op.drop_table('endorsements')
    op.drop_table('diners')
    # ### end Alembic commands ###
