"""Alter available at type to datetime

Revision ID: 72a4db0a082e
Revises: e6df5cb3f164
Create Date: 2023-08-24 16:05:49.646190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a4db0a082e'
down_revision: Union[str, None] = 'e6df5cb3f164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
