"""fix relationships

Revision ID: 7dd3eacc9a14
Revises: 0fc9421fd426
Create Date: 2023-08-24 12:10:28.622004

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7dd3eacc9a14'
down_revision: Union[str, None] = '0fc9421fd426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_restaurants_endorsements_restaurant_id', 'restaurants_endorsements', type_='foreignkey')
    op.drop_constraint('fk_restaurants_endorsements_endorsement_id', 'restaurants_endorsements', type_='foreignkey')
    op.create_foreign_key('fk_restaurants_endorsements_endorsement_id', 'restaurants_endorsements', 'endorsements', ['endorsement_id'], ['id'])
    op.create_foreign_key('fk_restaurants_endorsements_restaurant_id', 'restaurants_endorsements', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_restaurants_endorsements_restaurant_id', 'restaurants_endorsements', type_='foreignkey')
    op.drop_constraint('fk_restaurants_endorsements_endorsement_id', 'restaurants_endorsements', type_='foreignkey')
    op.create_foreign_key('fk_restaurants_endorsements_endorsement_id', 'restaurants_endorsements', 'restrictions', ['endorsement_id'], ['id'])
    op.create_foreign_key('fk_restaurants_endorsements_restaurant_id', 'restaurants_endorsements', 'diners', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
