"""feat: add booked at to reservations

Revision ID: a1793982238d
Revises: 6b8bfd043c9b
Create Date: 2023-08-24 20:58:06.066234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1793982238d'
down_revision: Union[str, None] = '6b8bfd043c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('booked_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'booked_at')
    # ### end Alembic commands ###
