"""Add is booked prop

Revision ID: cf70a4d8f49d
Revises: a1793982238d
Create Date: 2023-08-25 20:12:31.034301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf70a4d8f49d'
down_revision: Union[str, None] = 'a1793982238d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_booked')
    # ### end Alembic commands ###
